
type specializationArea = {
    name?: string;
    code?: string;
}

export const __specializationAreas: specializationArea[] = [
    { name: "Cardiology", code: "CR" },
    { name: "Neurology", code: "NR" },
    { name: "Orthopedics", code: "OR" },
    { name: "Pediatrics", code: "PD" },
    { name: "Dentistry", code: "DS" },
    { name: "Anesthesiology", code: "AS" },
    { name: "General Surgery", code: "GS" },
    { name: "Psychiatry", code: "PS" },
    { name: "Pharmacy", code: "PH" },
    { name: "Nursing", code: "NS" },
    { name: "Physical Therapy", code: "PT" },
    { name: "Veterinary Medicine", code: "VM" },
    { name: "Emergency Medicine", code: "EM" },
    { name: "Obstetrics and Gynecology", code: "OBG" },
    { name: "Ophthalmology", code: "OPH" },
    { name: "Gastroenterology", code: "GE" },
    { name: "Hematology", code: "HEM" },
    { name: "Infectious Disease", code: "ID" },
    { name: "Oncology", code: "ONC" },
    { name: "Radiology", code: "RAD" },
    { name: "Urology", code: "UR" },
    { name: "Dermatology", code: "DER" },
    { name: "Rehabilitation Medicine", code: "RM" },
    { name: "Surgical Nursing", code: "SN" },
    { name: "Pediatric Nursing", code: "PN" },
    { name: "Geriatric Nursing", code: "GN" },
    { name: "Critical Care Nursing", code: "CCN" },
    { name: "Public Health Nursing", code: "PHN" },
    { name: "Nurse Anesthetist", code: "NA" },
    { name: "Midwifery", code: "MW" },
    { name: "Nurse Practitioner", code: "NP" },
    { name: "Family Medicine", code: "FM" },
    { name: "Neonatal Nursing", code: "NN" },
    { name: "Mental Health Nursing", code: "MHN" },
    // { name: "Software Engineering", code: "SE" },
    // { name: "Data Science", code: "DS" },
    // { name: "Cybersecurity", code: "CS" },
    // { name: "Artificial Intelligence", code: "AI" },
    // { name: "Machine Learning", code: "ML" },
    // { name: "Cloud Computing", code: "CC" },
    // { name: "Database Management", code: "DB" },
    // { name: "Web Development", code: "WD" },
    // { name: "Mobile Development", code: "MD" },
    // { name: "Network Administration", code: "NA" },
    // { name: "DevOps", code: "DO" },
    // { name: "Quality Assurance", code: "QA" },
    // { name: "Game Development", code: "GD" },
    // { name: "Blockchain", code: "BC" },
    // { name: "UI/UX Design", code: "UIUX" },
    // { name: "Embedded Systems", code: "ES" },
    // { name: "Robotics", code: "RO" },
    // { name: "Digital Marketing", code: "DM" },
    // { name: "Project Management", code: "PM" },
    // { name: "Business Analysis", code: "BA" },
    // { name: "Product Management", code: "PM" },
    // { name: "Software Testing", code: "ST" },
    // { name: "Systems Engineering", code: "SE" },
    // { name: "IT Support", code: "ITS" },
    // { name: "Data Analytics", code: "DA" },
    // { name: "Cardiology", code: "CR" },
    // { name: "Neurology", code: "NR" },
    // { name: "Orthopedics", code: "OR" },
    // { name: "Pediatrics", code: "PD" },
    // { name: "Dentistry", code: "DS" },
    // { name: "Anesthesiology", code: "AS" },
    // { name: "General Surgery", code: "GS" },
    // { name: "Psychiatry", code: "PS" },
    // { name: "Pharmacy", code: "PH" },
    // { name: "Nursing", code: "NS" },
    // { name: "Physical Therapy", code: "PT" },
    // { name: "Veterinary Medicine", code: "VM" },
    // { name: "Law", code: "LW" },
    // { name: "Accounting", code: "AC" },
    // { name: "Human Resources", code: "HR" },
    // { name: "Marketing", code: "MK" },
    // { name: "Sales", code: "SL" },
    // { name: "Education", code: "ED" },
    // { name: "Architecture", code: "AR" },
    // { name: "Civil Engineering", code: "CE" },
    // { name: "Mechanical Engineering", code: "ME" },
    // { name: "Electrical Engineering", code: "EE" },
    // { name: "Chemical Engineering", code: "ChE" },
    // { name: "Financial Services", code: "FS" },
    // { name: "Real Estate", code: "RE" },
    // { name: "Humanitarian Aid", code: "HA" },
    // { name: "Social Work", code: "SW" },
    // { name: "Event Planning", code: "EP" },
    // { name: "Journalism", code: "JR" },
    // { name: "Public Relations", code: "PR" },
    // { name: "Culinary Arts", code: "CA" },
    // { name: "Fashion Design", code: "FD" },
    // { name: "Photography", code: "PH" },
    // { name: "Fine Arts", code: "FA" }
];